# Generated by Django 3.2.5 on 2021-07-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='char',
        ),
    ]
