# Generated by Django 3.2.5 on 2021-07-15 13:41

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
