# Generated by Django 3.2.5 on 2021-07-15 13:45

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210715_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, max_length=600),
        ),
    ]
