# Generated by Django 3.2.5 on 2021-07-15 13:51

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
