# Generated by Django 3.2.5 on 2021-07-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_short_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_content',
        ),
    ]
