# Generated by Django 3.2.5 on 2021-07-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Code Addiction', max_length=30),
        ),
    ]
