# Generated by Django 3.2.5 on 2021-07-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('content', models.TextField(max_length=300)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
